### PR TITLE
china tweaks

### PR DESCRIPTION
**Pull request by udeved**
* add champion swordsman, archer and chariot buildable in fortress and fortified civil center
* fix garrison flags
* add champion tech to switch weapons
* don't use visual garrison holder slots in towers and gates
* tweak chinese govt techs and lower requirement to town phase

### CODE REVIEW

**Comment by StanleySweet** [comment]
The gate garisonning is intended. That's a bug in the main game. See https://code.wildfiregames.com/D1418 for current status.
What do you mean by switch weapons ?

**Comment by udeved** [comment]
Regarding the weapon switch tech, I also ported the tech from DE, but removed the pairing, ie only one tech to research and no either/or alternative.
The tech enable champion archers to switch to swords, similar how the xiongnu warlord work to switch weapons. So champion archer and swordsman can be switched between the two.
No sure how trampling works, and if...

**Comment by udeved** [comment]
I basically took arts from DE mod, I am a programmer, no really talented with arts and lack of time. ;)

**Comment by lionkanzen** [comment]
I think is referring switch weapon between range and melee is there a ticket with that.

**Pull request merged**
