### PR TITLE
More descriptive readme

### PR DESCRIPTION
**Pull request by Jeeppler**
I rewrote the `Readme.md` with the goal to make it more descriptive and inviting for people unfamiliar with 0 A.D. or the Terra Magna mod.

### CODE REVIEW

**Comment by StanleySweet** [comment]
Hey Jeepler thanks for your interest in this.
I'm not sure I've heard from you, Do you have any other name on the forums ?

Some comments  I don't think we will include the kushites in the mod so you can remove that.

fraction → faction

tasks finish the zapotec, xiognu, and chinese factions
Alpha 23 Ken wood

**Comment by Jeeppler** [comment]
@StanleySweet is there any reason not to include the Kushites?

**Comment by Jeeppler** [comment]
@StanleySweet I will add your recommended changes.

**Comment by Jeeppler** [comment]
@StanleySweet are you differentiating between Xiognu and other chinese factions and if so, what is reason?

**Comment by Jeeppler** [comment]
@StanleySweet Please review the readme again. I added your suggestions into the readme.

**Comment by StanleySweet** [comment]
> are you differentiating between Xiognu and other Chinese factions and if so, what is reason?
Well because chinese are mostly han :)
>

**Pull request merged**
