### PR TITLE
Update model names

### PR DESCRIPTION
**Pull request by dmouse**
In the new 0Ad version a lot of Entities were renamed and remove, this PR solve some of them

### CODE REVIEW

**Comment by dmouse** [comment]
any feedback @StanleySweet

**Comment by StanleySweet** [comment]
The zebu change is wrong as they will always  pop the same one.

**Comment by dmouse** [comment]
Got it, I going to use the `zebu_wild.xml` and `zebu.xml`, thanks!

**Comment by dmouse** [comment]
close in favor of #72

**Pull request closed without merging**
